name: Jekyll site CI

on:
  workflow_dispatch:
env: 
    SSHPASS: "zorrozorro123"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run:  |   
                sudo apt update
                sudo apt install sshpass
                sshpass -p zorrozorro123 scp -P 22 ./* ubuntu@3.18.106.74:/usr/share/nginx/html/
           
