name: "Destroy"
on: [workflow_dispatch]
# on:
#   push:
#     branches:
#       - main
jobs:
  AutoTerraformDestroy:
  #Init and Apply creation full infrastructure
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@newpage

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - run: sed -i "s/TOKEN/${{secrets.TOKEN}}/g" bash.sh

      #----------------------------
    - name: Terraform Init
      env:
            AWS_ACCESS_KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
            AWS_SECRET_ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      run: terraform init

    - name: Terraform Destroy
      env:
          AWS_ACCESS_KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      run: terraform destroy
