name: "Autoterraform EC2"
on: [workflow_dispatch]
                            # on:
                            #   push:
                            #     branches:
                            #       - main
jobs:
  AutoEC2:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repos
        uses: actions/checkout@main
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - run: sed -i "s/TOKEN/${{secrets.TOKEN}}/g" bash.sh
            #----------------------------
      - name: Terraform init
        env :
              AWS_ACCESS_KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -input=false

            #----------------------------
      - name: Terraform destroy
        env :
              AWS_ACCESS_KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY }}        
        run: terraform destroy -auto-approve
              #------------------------
